src/controllers/asistenteController.py
# src/controllers/asistenteController.py
from flask import render_template
from src.controllers.baseController import BaseController

class AsistenteController(BaseController):
    def __init__(self, app):
        prefix = '/asistente'
        super().__init__(app, 'asistente')
        
        self.app.route('/asistente', methods=['GET', 'POST'])(self.asistente)

    def asistente(self):
        # tu lógica aquí
        return render_template('asistente.html')

src/controllers/baseController.py
# src/controllers/baseController.py
from flask import Blueprint, redirect, render_template, session
from datetime import datetime, timedelta

class BaseController:
    def __init__(self, app, prefix):
        self.app = app
        self.prefix = prefix
        self.blueprint = Blueprint(self.prefix, __name__)

        # Añadir funciones comunes
        self.blueprint.before_request(self.before_request)

    def route(self, rule, **options):
        def decorator(f):
            self.blueprint.route(rule, **options)(f)
            return f
        return decorator

    def get_blueprint(self):
        return self.blueprint

    def before_request(self):
        # Función que se ejecuta antes de cada solicitud
        # Puedes poner aquí lógica común para todos los controladores, por ejemplo, verificar la sesión del usuario
        pass

    def formatear_fecha(self, fecha):
        fecha_actual = datetime.now()

        if fecha_actual.date() == fecha.date():
            return f'Hoy a las {fecha.strftime("%H:%M")}'
        elif fecha_actual.date() - timedelta(days=1) == fecha.date():
            return f'Ayer a las {fecha.strftime("%H:%M")}'
        else:
            return fecha.strftime("%d/%m/%Y %H:%M")
        
   
    
    def get_app(self):
        return self.app

src/controllers/carritoController.py
# src/controllers/carritoController.py
from flask import render_template, flash, redirect, url_for, session
from src.controllers.baseController import BaseController
from src.models.ventasModel import VentasModel
from src.models.comprasModel import ComprasModel

class CarritoController(BaseController):
    def __init__(self, app):
        prefix = '/carrito'
        super().__init__(app, prefix)
        self.ventas_model = VentasModel(self.app, "prefix")
        self.compras_model = ComprasModel(self.app, "prefix")
        self.app.route('/carrito', methods=['GET'])(self.ver_carrito)
        self.app.route('/carrito/comprar', methods=['POST'])(self.comprar)

    def ver_carrito(self):
        try:
            if 'username' not in session:
                flash('Debes iniciar sesión para ver tu carrito.', 'error')
                return redirect(url_for('login'))  # Reemplaza 'login' con la ruta real de inicio de sesión

            username = session['username']

            # Obtener los productos en el carrito del usuario desde la base de datos
            productos_carrito = self.ventas_model.get_productos_en_carrito(username)

            return render_template('carrito.html', productos_carrito=productos_carrito)

        except Exception as error:
            print(f'Error: {str(error)}')
            flash(f'Error: {str(error)}', 'error')
            return redirect(url_for('carrito')), 500

    def comprar(self):
        try:
            if 'username' not in session:
                flash('Debes iniciar sesión para comprar.', 'error')
                return redirect(url_for('login'))  # Reemplaza 'login' con la ruta real de inicio de sesión

            username = session['username']

            # Obtener los productos en el carrito del usuario desde la base de datos
            productos_carrito = self.ventas_model.get_productos_en_carrito(username)

            if productos_carrito:
                # Registrar la compra en la tabla de compras
                compra_id = self.compras_model.registrar_compra(username)

                # Mover los productos comprados de la tabla de ventas a la tabla de compras
                for producto in productos_carrito:
                    self.compras_model.registrar_producto_comprado(compra_id, producto)

                # Eliminar los productos comprados del carrito del usuario
                self.ventas_model.eliminar_productos_comprados(username)

                flash('Compra realizada correctamente.', 'success')
            else:
                flash('El carrito está vacío. Agrega productos antes de comprar.', 'warning')

        except Exception as error:
            print(f'Error: {str(error)}')
            flash(f'Error: {str(error)}', 'error')

        return redirect(url_for('carrito'))

src/controllers/comentariosController.py
#--------------------------------------------------------------------------------------------------------------------------
#  *                                                      INFO
#    
#    Finalmente, en el controlador (comentariosController.py), utilizaremos la entidad y el modelo para manejar la lógica de la aplicación.
#    
# 
#--------------------------------------------------------------------------------------------------------------------------


# src/controllers/comentariosController.py
from flask import flash, redirect, request, render_template, url_for, session
from src.controllers.baseController import BaseController
from src.models.comentarioModel import ComentarioModel
from src.entities.comentarioEntity import ComentarioEntity
from datetime import datetime

import pytz

class ComentariosController(BaseController):
    def __init__(self, app):
        prefix = '/comentarios'
        super().__init__(app, prefix)

        # Registro de rutas
        self.app.route('/comentarios', methods=['GET', 'POST'])(self.comentarios)

    def comentarios(self):
        try:
            if request.method == 'POST':
                usuario = session.get('username')
                comentario = request.form['comentario']

                if usuario:
                    if ComentarioModel.insert_comentario(usuario, comentario):
                        return redirect('/comentarios')
                    else:
                        flash("Error al insertar comentario. Intenta de nuevo.", "error")
                        return redirect(url_for('comentarios.comentarios'))
                else:
                    flash('Necesitas iniciar sesión para comentar.', 'info')
                    return redirect(url_for('login'))

            elif request.method == 'GET':
                comentarios_list = ComentarioModel.get_comentarios(self)
                username = session.get('username', None)
                return render_template('comentarios.html', username=username, comentarios=comentarios_list)

        except Exception as e:
            print(f"Error en la función 'comentarios': {str(e)}")
            flash(f"Error interno del servidor: {str(e)}", "error")
            return redirect(url_for('comentarios.comentarios'))
        
        
        
        
        

src/controllers/comprasController.py
from flask import render_template
from src.controllers.baseController import BaseController

class ComprasController(BaseController):
    def __init__(self, app):
        prefix = '/compras'
        super().__init__(app, 'compras')
        
        self.app.route('/compras', methods=['GET', 'POST'])(self.compras)

    def compras(self):
        # tu lógica aquí
        return render_template('compras.html', datos='AlgunosDatos')

src/controllers/contactoController.py
#--------------------------------------------------------------------------------------------------------------------------
#  *                                                      INFO
#    
#    Este archivo se encarga de manejar las solicitudes relacionadas con la funcionalidad de contacto.
#    
# 
#--------------------------------------------------------------------------------------------------------------------------


# src/controllers/contactoController.py
from flask import render_template, request, flash
from src.controllers.baseController import BaseController
from src.models.contactoModel import ContactoModel
from src.entities.contactoEntity import ContactoEntity
from email.mime.text import MIMEText

from flask import flash, redirect, request, render_template, url_for, session

import smtplib

class ContactoController(BaseController):
    def __init__(self, app):
        prefix = '/contacto'
        super().__init__(app, prefix)

        self.app.route('/contacto', methods=['GET', 'POST'])(self.contacto)

    def send_email(self, nombre, email, mensaje):
        
        try:
            smtp_server = 'sandbox.smtp.mailtrap.io'
            smtp_port = 587
            smtp_username = 'd7c58f9278522e'
            smtp_password = 'f3d2c0db06c990'

            msg = MIMEText(f'Nombre: {nombre}\nEmail: {email}\nMensaje: {mensaje}')
            msg['Subject'] = 'Nuevo mensaje del formulario de contacto'
            msg['From'] = 'Contactame@dulces.promesas.com'
            msg['To'] = 'MailTrap@inbox.mailtrap.io'

            server = smtplib.SMTP(smtp_server, smtp_port)
            server.starttls()
            server.login(smtp_username, smtp_password)
            server.sendmail(msg['From'], [msg['To']], msg.as_string())
            server.quit()

            return True
        except Exception as e:
            print(f'Error al enviar el correo: {str(e)}')
            return False

    def contacto(self):
        
        try:
            if request.method == 'POST':
                nombre = request.form['nombre']
                email = request.form['email']
                mensaje = request.form['mensaje']

                # Crear una instancia de ContactoEntity
                contacto_entity = ContactoEntity(nombre=nombre, email=email, mensaje=mensaje)

                # Usar ContactoModel para insertar en la base de datos
                if ContactoModel.insert_contacto(contacto_entity):
                    # Enviar correo
                    if self.send_email(nombre, email, mensaje):
                        error_message = "Se han enviado correctamente los datos."
                        return render_template('contacto.html', error_message=error_message)
                    else:
                        flash("Error al enviar correo. Intenta de nuevo.", "error")
                        return render_template('contacto.html')

        except Exception as error:
            print(f'Error: {str(error)}')
            flash(f'Error: {str(error)}', 'error')
            return render_template('contacto.html'), 500
        
        username = session.get('username', None)
        return render_template('contacto.html', username=username)

src/controllers/loginController.py
#--------------------------------------------------------------------------------------------------------------------------
#  *                                                      INFO
#    
#    En este archivo, se define la clase LoginController, que hereda de BaseController. Esta clase tiene un método llamado login, que maneja la lógica del inicio de sesión. En este método, se obtienen las credenciales del formulario, se crea una instancia de LoginEntity y se utiliza el método authenticate_user de LoginModel para verificar si las credenciales son válidas.
#    
# 
#--------------------------------------------------------------------------------------------------------------------------


# src/controllers/loginController.py
from flask import redirect, request, render_template, session
from src.controllers.baseController import BaseController
from src.models.loginModel import LoginModel
from src.entities.loginEntity import LoginEntity

class LoginController(BaseController):
    def __init__(self, app):
        # Define el prefijo para este controlador, por ejemplo, '/login'
        prefix = '/login'
        super().__init__(app, prefix)
        # Configuración de la ruta
        self.app.route('/login', methods=['GET', 'POST'])(self.login)

    def login(self):
        # Lógica del login
        if request.method == 'POST':
            username = request.form['username']
            password = request.form['password']

            login_entity = LoginEntity(username=username, password=password)
            if LoginModel.authenticate_user(login_entity.username, login_entity.password):
                session['username'] = username
                return redirect('/index')
            else:
                error_message = "Credenciales incorrectas. Intenta de nuevo."
                return render_template('login.html', error_message=error_message)

        return render_template('login.html')

src/controllers/logoutController.py
from flask import Blueprint, render_template, session, redirect, url_for

class LogOutController:
    def __init__(self, app):
        self.blueprint = Blueprint('logout', __name__, url_prefix='/logout')

        @self.blueprint.route('/cerrar_sesion')
        def cerrar_sesion():
            session.clear()
            return redirect('/')  # Redirige a la página de inicio u otra página

    def get_blueprint(self):
        return self.blueprint

src/controllers/nosotrosController.py
# src/controllers/nosotrosController.py
from flask import render_template
from src.controllers.baseController import BaseController
from flask import flash, redirect, request, render_template, url_for, session

class NosotrosController(BaseController):
    def __init__(self, app):
        prefix = '/nosotros'
        super().__init__(app, 'nosotros')
        
        self.app.route('/nosotros', methods=['GET', 'POST'])(self.nosotros)

    def nosotros(self):
        # tu lógica aquí
        
        username = session.get('username', None)
        return render_template('nosotros.html', username=username, datos='AlgunosDatos')

src/controllers/registroController.py
#--------------------------------------------------------------------------------------------------------------------------
#  *                                                      INFO
#    
#    En este archivo, se define la clase RegistroController, que hereda de BaseController. La clase tiene un método llamado registro, que maneja la lógica del registro. En este método, se obtienen las credenciales del formulario, se crea una instancia de RegistroEntity y se utiliza el método register_user de RegistroModel para realizar el registro en la base de datos.
#    
# 
#--------------------------------------------------------------------------------------------------------------------------


# src/controllers/registroController.py
import re
from flask import redirect, request, render_template
from src.controllers.baseController import BaseController
from src.models.registroModel import RegistroModel
from src.entities.registroEntity import RegistroEntity

class RegistroController(BaseController):
    def __init__(self, app):
        prefix = '/registro'
        super().__init__(app, prefix)

        self.app.route('/registro', methods=['GET', 'POST'])(self.registro)
    
    def validate_password(self, password):
        if len(password) < 8:
            return False
        if not re.search(r"\d", password):
            return False
        if not re.search(r"[a-z]", password):
            return False
        if not re.search(r"[A-Z]", password):
            return False
        if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
            return False
        return True

    def registro(self):
        if request.method == 'POST':
            username = request.form['username']
            password = request.form['password']
            email = request.form['email']

            # Validar la contraseña antes de intentar el registro
            if not self.validate_password(password):
                error_message = "La contraseña no cumple con los requisitos. Intenta de nuevo."
                return render_template('registro.html', error_message=error_message)

            registro_entity = RegistroEntity(username=username, password=password, email=email)
            if RegistroModel.register_user(registro_entity.username, registro_entity.password, registro_entity.email):
                return redirect('/login')
            else:
                return "Error al registrar. Intenta de nuevo."

        return render_template('registro.html')

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}Mi Sitio{% endblock %}</title>
</head>

<body>
    <!-- Contenido común de todas las páginas -->

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <!-- Mostrar comentarios -->
    <h2>Comentarios</h2>
    <ul>
        {% for comentario in comentarios %}
        <li>{{ comentario.usuario }}: {{ comentario.comentario }}</li>
        {% endfor %}
    </ul>

</body>

</html>

templates/comentarios.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="/static/web/css/estilos.css">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <!--<link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jost&display=swap" rel="stylesheet">
    <!--<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">-->
    <link type="image/png" rel="icon" href="../static/web/img/logo/Dulces promesas.jpg">
    <link rel="stylesheet" href="/static/web/css/productos.css">
    <link rel="stylesheet" href="static\web\css\comentarios.css">
    <title>Comentarios</title>
    </head>

<body>
    <header data-aos="fade-down" data-aos-duration="2000">
        <article class="contHeader">
            <section class="perfilHeader">
    
                <a href="{{ url_for('login') }}"><img src="/static/web/img/perfil.png" class="perfil" alt="perfil"></a>
                <i class='bx bx-chevron-down bx-md'></i>
    
                <div class="perfil-name">
                    {% if username %}
                    <p>Bienvenido, {{ username }}!</p>
                    {% else %}
                    <p>Bienvenido al sitio web!</p>
                    {% endif %}
                </div>
            </section>
    
            <nav>
    
                <ul class="direcciones">
                    <li><a href="{{ url_for('index.index') }}">Inicio</a></li>
                    <!--<li><a href="{{ url_for('compras') }}">Pedidos Online</a></li>-->
                    <li><a href="{{ url_for('contacto') }}">Contacto</a></li>
                    <li><a href="{{ url_for('nosotros') }}">Nosotros</a></li>
                    <li><a href="{{ url_for('comentarios') }}">Comentarios</a></li>
                    <li><a href="{{ url_for('productos') }}">Productos</a></li>
                    <!--<li><a href="{{ url_for('asistente') }}">Asistente</a></li>-->
    
    
                </ul>
    
            </nav>
    
            <section class="redesHeader">
    
                <div class="redes">
                    <a href="https://www.facebook.com/profile.php?id=61551121165907" target="_blank"><i
                            class='bx bxl-facebook bx-sm'></i></a>
                    <a href="#"><i class='bx bxl-whatsapp bx-sm'></i></a>
                    <a href="#"><i class='bx bxl-pinterest-alt bx-sm'></i></a>
                    <a target="_blank"
                        href="https://www.instagram.com/dulces_promesas_oficial/?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D"><i
                            class='bx bxl-instagram bx-sm'></i></a>
                </div>
            </section>
        </article>
    
    </header>

    <div class="contLine" data-aos="fade-down" data-aos-duration="2000">
        <div class="linea"></div>
    </div>
    <div class="sup-contenedor-comentarios">
    <article class="titulo">
    <h1>Comentarios</h1>
    </article>




        <form method="post" action="/comentarios">
            <textarea class="textarea-comentario" name="comentario" rows="4" cols="50" required></textarea>
            <button type="submit" class="boton-enviar">
                <img src="static\web\img\svg\Send--Streamline-Platinum.svg" alt="Publicar comentario">
            </button>
        </form>

        {% if usuario %}
        <p>Bienvenido, {{ usuario }}. Deja tu comentario:</p>
        <!--<form method="post" action="/comentarios">
            <textarea name="comentario" rows="4" cols="50" required></textarea><br>
            <input type="submit" value="Publicar comentario">
        </form>-->
        
        <hr>
        {% endif %}






        <div class="sup-comentarios">
            {% if comentarios %}
            <ul>
                {% for comentario in comentarios %}
                <div class="contenido-comentario">{{ comentario.usuario }} ({{ comentario.fecha }}):</div> <br> <div class="txt-comentarios"> <div class="ajuste-txt"> {{ comentario.comentario }}</div></div> <br>
                {% endfor %}
            </ul>
            {% else %}
            <p>No hay comentarios aún.</p>
            {% endif %}
    </div>

</div>
</body>

</html>

templates/completado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Gracias por su compra</h1>
</body>
</html>

templates/confirmacion_compra.html
<!-- templates/confirmacion_compra.html -->
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmación de Compra</title>
</head>

<body>
    <h1>¡Gracias por tu compra!</h1>
    <p>Tu compra ha sido realizada con éxito.</p>
    <!-- Puedes agregar más detalles de confirmación si lo deseas -->
</body>

</html>

templates/historial_compras.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Gracias por comprar
    <li><a href="{{ url_for('index.index') }}">Inicio</a></li>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="/static/web/css/estilos.css">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Jost&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link type="image/png" rel="icon" href="../static/web/img/logo/Dulces promesas.jpg">
    <link rel="stylesheet" href="../static/web/css/logout.css">
    <title>"Las Dulces Promesas"</title>
</head>
<body>
    
    <header data-aos="fade-down" data-aos-duration="2000">
        <article class="contHeader">
            <section class="perfilHeader">

                <a href="{{ url_for('login') }}"><img src="/static/web/img/perfil.png" class="perfil" alt="perfil"></a>
                <a href="{{ url_for('logout.cerrar_sesion') }}">
                    <i class='bx  bx-md log-out-i'>
                        <div class="options"><img src="../static/web/img/svg/Navigation-Menu-Vertical-1--Streamline-Ultimate.svg" alt=""></div>
                        <div class="log-out"><img src="..\static\web\img\svg\User-Logout--Streamline-Ultimate.svg" alt=""></div>
                    </i>
                    
                </a>

                <div class="perfil-name">
                    {% if username %}
                    <p>Bienvenido, {{ username }}!</p>
                    {% else %}
                    <p>Bienvenido al sitio web!</p>
                    {% endif %}
                </div>

            </section>

            <nav>

                <ul class="direcciones">
                    <li><a href="{{ url_for('index.index') }}">Inicio</a></li>
                    <!--<li><a href="{{ url_for('compras') }}">Pedidos Online</a></li>-->
                    <li><a href="{{ url_for('contacto') }}">Contacto</a></li>
                    <li><a href="{{ url_for('nosotros') }}">Nosotros</a></li>
                    <li><a href="{{ url_for('comentarios') }}">Comentarios</a></li>
                    <li><a href="{{ url_for('productos') }}">Productos</a></li>
                    <!--<li><a href="{{ url_for('asistente') }}">Asistente</a></li>-->
                    

                </ul>

            </nav>

            <section class="redesHeader">

                <div class="redes">
                    <a href="https://www.facebook.com/profile.php?id=61551121165907" target="_blank"><i class='bx bxl-facebook bx-sm'></i></a>
                    <a href="#"><i class='bx bxl-whatsapp bx-sm'></i></a>
                    <a href="#"><i class='bx bxl-pinterest-alt bx-sm'></i></a>
                    <a target="_blank" href="https://www.instagram.com/dulces_promesas_oficial/?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D"><i class='bx bxl-instagram bx-sm'></i></a>
                </div>
            </section>
        </article>

    </header>

    <div class="contLine" data-aos="fade-down" data-aos-duration="2000">
        <div class="linea"></div>
    </div>

<!-----------Cuerpo-------------->
    
    <section class="centro">

        <article class="contCentro">

            <section class="contPrincipal">

                <article class="title">
                    <h1>Las Dulces Promesas</h1>
                </article>

                <article class="presentacion" data-aos="fade-up""
                data-aos-duration="2000">

                    <div class="contImg">
                        <div class="preImagen start"><img src="/static/web/img/imgUno.png" class="imagen" alt=""></div>
                    </div>

                    <div class="contImg textoImg">
                        <img src="/static/web/img/imgDos.png" class="imagen">
                           
                            <div class="boton-encima"><button class="pedido"><a href="compras.html"> Hacer un pedido </a></button></div>
                    </div>

                    <div class="contImg">
                        <div class="preImagen end"><img src="/static/web/img/imgTres.png" class="imagen" alt=""></div>
                    </div>

                </article>

            </section>


            <section class="contSecundario">
                
                <article class="subTexto">
                    <div class="contTexto">
                        <h2>PASTELES DISEÑADOS A TU GUSTO Y ESTILO</h2>
                    </div>
                </article>

                <article class="secciones">

                    <div class="contSecciones" data-aos="fade-up" data-aos-duration="2000" data-aos-anchor-placement="top-bottom" >
                        <div class="contMover">
                            <div class="conocer caja">
                                <img src="/static/web/img/conocenos.png" class="secImg" alt="">
                                <div class="botonDentro izq"><a href="nosotros.html"><button class="botoncito">Conócenos</button></div></a>
                            </div>

                            <div class="contactar caja">
                                <img src="/static/web/img/contactanos.png" class="secImg" alt="">
                                <div class="botonDentro der"><a href="contacto.html"><button class="botoncito">Contáctanos</button></div></a>
                            </div>
                        </div>
                    </div>

                </article>
            </section>

            <section class="contTerceario"  data-aos="fade-up" data-aos-duration="2000" data-aos-anchor-placement="top-bottom">

                <article class="siguenos">
                    <div class="siguenosText"><h2>Síguenos en nuestras Redes Sociales</h2></div>
                    <br>
                    <div class="contPostres">
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 13.png" class="enseñar" alt="">
                            <div class="textUp">CupCake</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 14.png" class="enseñar" alt="">
                            <div class="textUp">Tarta <br> Chantillí</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 15.png" class="enseñar" alt="">
                            <div class="textUp">Tarta de <br> Fresas</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 16.png" class="enseñar" alt="">
                            <div class="textUp">Queque <br> Chantillí</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 17.png" class="enseñar" alt="">
                            <div class="textUp">Queque <br> Chocolate</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 18.png" class="enseñar" alt="">
                            <div class="textUp">Helado</div>
                        </div>
                        <div class="contimage">
                            <img src="/static/web/img/Siguenos/Rectangle 19.png" class="enseñar" alt="">
                            <div class="textUp">Pastel Tres <br> Leches</div>
                        </div>
                    </div>

                </article>
            </section>
        </article>
    </section>

    <footer>

        <article class="redesSociales">

            <div class="contRedes" data-aos="zoom-in" data-aos-duration="1500">
                
                <a target="_blank" href="https://www.instagram.com/dulces_promesas_oficial/?utm_source=qr&igshid=MzNlNGNkZWQ4Mg%3D%3D" class="red ig"><img src="/static/web/img/Redes/instagram (2).png" class="redSocial" alt=""></a>

                <a href="https://www.facebook.com/profile.php?id=61551121165907" target="_blank" class="red fb"><img src="/static/web/img/Redes/facebook.png" class="redSocial" alt=""></a>

                <a href="#" class="red tw"><img src="/static/web/img/Redes/gorjeo (1).png" class="redSocial" alt=""></a>

                <a href="#" class="red tk"><img src="/static/web/img/whatsapp.png" class="redSocial" alt=""></a>

            </div>

        </article>

        <article class="derechosAutor">

            


        </article>

    </footer>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
    AOS.init();
    </script>

    <script src="/static/web/js/app.js"></script>
</body>
</html>